### ISSUE TITLE
Docker Dock

### ISSUE THREAD

**Issue by grand-oma** [grand-mother/grand#34]
Hi Jean-Marc, thanks for the nice documentation on Docker.
One small issue thoiugh: your link to Docker images of GRANDLIB points to https://hub.docker.com/, which is kind of a homepage. Shouldn't it be https://hub.docker.com/r/jcolley/grandlib_eclipse?

Thanks 
Olivier
PS: solution 1 for display did not work for me (Ubuntu 18.04 on a VirtualBox) but solution 2 did.

**Comment by luckyjim** [comment]
Hi, 
Thank
in fact the good link is : https://hub.docker.com/u/jcolley
with the 4 docker image
eventually I would move to a specific GRANDLIB link (not jcolley) or more naturally to a github repository if the use remains simple (to be studied)

**Comment by luckyjim** [comment]
wiki modification is done
https://github.com/grand-mother/grand/wiki/docker_quickstart#pull-a-grandlib-image-from-dockerhub
