### ISSUE TITLE
Reserved keyword in dataclass

### ISSUE THREAD

**Issue by ifleg** [grand-mother/grand#48]
In class ShowerEventTree and ShowerEventSimdataTree we have a property called "date".
As date is a reserved keyword in many laguages it will lead to problems (for example it's forbidden to name a column "date" in a database).
I suggests to rename it (maybe in event_date).

**Comment by lwpiotr** [comment]
@grand-oma @mjtueros @luckyjim @pmitra-astro @rameshkoirala @niess
