### ISSUE TITLE
Source env/setup.sh always remakes the files

### ISSUE THREAD

**Issue by lwpiotr** [grand-mother/grand#61]
Related to #59 

The first time the `source env/setup.sh` is executed the "Install external lib gull and turtle" should be executed of course, but for the next times, it should be skipped and the script should just set the environment. Or the readme should say, that `source env/setup.sh` should be executed just when running for the first time, and then some other script should be sourced just to set up the environment in the following uses.

**Comment by luckyjim** [comment]
Hello, 

There is this pitfall with env/setup.sh that I don't know how to fix easily, so I added a make clean
I don't remember exactly the problem ...
I remove the make clean 
[e84c92c](https://github.com/grand-mother/grand/commit/e84c92cedd3bd6ca070ca0f3a1f230ad77d8ae4d)
and  I'm waiting for someone to come back to the problem to correct it more properly

Check and close please

**Comment by lwpiotr** [comment]
I've already closed this. When someone again encounters a problem, we will learn how to reproduce it and then fix.

**Comment by grand-oma** [comment]
William Erba (intren at ICRR) seems to have fallen in this problem at installation time
Error:
  File "/home/grand/grand/geo/turtle.py", line 12, in <module>
    from .._core import ffi, lib
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/grand/grand/../lib/libturtle.so)

All good after full clean + reinstal following JM's advice.
