### ISSUE TITLE
add on sim2root command line an option to specify run number and event number

### ISSUE THREAD

**Issue by mjtueros** [grand-mother/grand#70]
When merging simulations and creating libraries you might want to change the run number and the event number.
For example in my last library all events were asigned run 0 and event 1 at the time of producing the rawroot file, and when creating the grandroot file i would have liked to change the event number to something different for each event.

**Comment by lwpiotr** [comment]
Added an option in dev_sim2root branch. Please check.

**Comment by mjtueros** [comment]
checked, it works, thanks!
