### ISSUE TITLE
trace extension and undersampling to get to ADC traces in efeld2voltage

### ISSUE THREAD

**Issue by mjtueros** [grand-mother/grand#73]
efield2voltage is missing the implementation of the ADC, and in particular to be able to handle traces that are not the same lenght as the hardware lenght.

**Comment by jelenakhlr** [comment]
I just created another branch "dev_downsample_and_ADCconversion_Jelena" and wrote functions for ADC conversion, downsampling and padding and included them in convert_efield_to_voltage.py

I would appreciate any feedback :)

**Comment by mjtueros** [comment]
we ended up using the script made by pablo, convert_voltage2adc.py, that also includes the posibility to add measured noise.
