### ISSUE TITLE
sim2root is not separating the trees in files, and has no option for filenames.

### ISSUE THREAD

**Issue by mjtueros** [grand-mother/grand#74]
- as in the tilte
- the objective is 
- to have automatic filenaming as per the data managament rules, and an override function to give an output filename.
- to to output a simshower file with the trees asociated to the shower simulation, and a second simefiled file with the trees asociated to the efield simulation.

As a side projet, i will modify zhaires rawroot script to give the appropiate (ie unique) id to the antennas.

**Comment by lwpiotr** [comment]
Most of it should be fixed now in sim2root branch. Directory name can be overwritten, but I am not sure how we would overwrite file name, as there are multiple files now. Some patter? Or maybe not needed with directory name overwriting? I am also not sure what the 4th point means.

**Comment by mjtueros** [comment]
4th point meant not having all the trees in separate directories, but asociate related trees on the same file.
with point 3 i meant that the sim2root tree automatially names the file (using the simulation infomation and the database rules) but we keep an option to manually set the file name, for tests and special cases.

**Comment by mjtueros** [comment]
this has been solved, and merged into branch 73_dev_.... I will delete branch 74_dev_...
