### ISSUE TITLE
Error when call el.get_event()

### ISSUE THREAD

**Issue by watertien** [grand-mother/grand#97]
Error message: 'Event' object has no attribute 'thower'
Likely from a typo in the code, "thower" is not in the TTree.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 el.get_event()

File ~/grand/grand/grandlib_classes/grandlib_classes.py:1121, in EventList.get_event(self, event_number, run_number, entry_number, fill_event, **kwargs)
   1119     e.fill_event_from_trees(init_trees=self.init_trees, **kwargs)
   1120 else:
-> 1121     e.fill_event_from_trees(init_trees=self.init_trees, **self.init_kwargs)
   1123 # Don't init trees anymore
   1124 self.init_trees = False

File ~/grand/grand/grandlib_classes/grandlib_classes.py:564, in Event.fill_event_from_trees(self, event_number, run_number, entry_number, simshower, use_trawvoltage, trawvoltage_channels, init_trees)
    561             self.tshower = None
    563 # If self.t(sim)shower was successfully initialised
--> 564 if (simshower and self.tsimshower is not None) or (not simshower and self.thower is not None):
    565     # Fill part of the event from tshower
    566     ret = self.fill_event_from_shower_tree(simshower)
    567     if ret:

AttributeError: 'Event' object has no attribute 'thower'`

**Comment by lwpiotr** [comment]
Fixed the typo and pushed. Please recheck.

**Comment by watertien** [comment]
After correcting "thower" to "tshower", a new error pops up.

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[4], line 1
----> 1 el.get_event()

File ~/grand/grand/grandlib_classes/grandlib_classes.py:1121, in EventList.get_event(self, event_number, run_number, entry_number, fill_event, **kwargs)
   1119     e.fill_event_from_trees(init_trees=self.init_trees, **kwargs)
   1120 else:
-> 1121     e.fill_event_from_trees(init_trees=self.init_trees, **self.init_kwargs)
   1123 # Don't init trees anymore
   1124 self.init_trees = False

File ~/grand/grand/grandlib_classes/grandlib_classes.py:600, in Event.fill_event_from_trees(self, event_number, run_number, entry_number, simshower, use_trawvoltage, trawvoltage_channels, init_trees)
    597             # Make tsimshower really None
    598             self.tsimshower = None
--> 600 self.fill_antennas()

File ~/grand/grand/grandlib_classes/grandlib_classes.py:646, in Event.fill_antennas(self)
    644 if self.tefield is not None: event_dus_indices = self.tefield.get_dus_indices_in_run(self.trun)
    645 elif self.tvoltage is not None: event_dus_indices = self.tvoltage.get_dus_indices_in_run(self.trun)
--> 646 for i in range(len(event_dus_indices)):
    647     a = Antenna()
    648     ant_ind = int(event_dus_indices[i])

UnboundLocalError: local variable 'event_dus_indices' referenced before assignment

**Comment by lwpiotr** [comment]
OK, please provide a way to reproduce this behaviour: code, files which the code tries to read, etc.

**Comment by watertien** [comment]
Data file: /sps/grand/data/gp13/GrandRoot/2024/04/GP13_20240428_150018_RUN127_UD_RAW_ChanXYZ_20dB_13dus_BeaconTest_100M_001.root
Code:
`fname = "GP13_20240428_150018_RUN127_UD_RAW_ChanXYZ_20dB_13dus_BeaconTest_100M_001.root"
el = EventList(fname)
el.get_event()`
